### ISSUE TITLE
White squares on vehicles.

### ISSUE THREAD

**Issue by JavikN7** [djchill1/Los_Angeles_Mod_v2.1_-_DJ#9]
**Description**
Most units have white square when their sirenlights are on. I assume it's because I have to install LED submod. But I can't register on the emergency-planet (not receiving the confirmation e-mail). Maybe I'm wrong and it's something else that is missing, please clarify.

**Desired solution**
Name or up-to-date links for missing content to fix white squares on the vehicle's siren lights.

**Comment by ChevetOverTheMoon** [comment]
If you haven't found the solution yet, you need the files here.
https://www.moddb.com/mods/mayberry-mod-2014/addons/corona-update

**Comment by JavikN7** [comment]
Thank you for sending that even though it's been so long. I hope it will help someone else as well.
